/* Generated by c2math (FR-008) */
int sort(int cmp, int arr, int n);
int mk(void);
int log_msg(int fmt);

int sort(int cmp, int arr, int n) { /* no body */ }

int mk(void) { /* no body */ }

int log_msg(int fmt) { /* no body */ }

