/* Generated by c2math (FR-008 + FR-009 types) */

enum E {
  A = 1,
  B = 2,
  C = 5
};

struct S {
  int a;
  unsigned int b : 3;
  char name[16];
  int *p;
};

typedef int (*cmp_t)(void *, void *);

static int *gp;
char buf[16];

int sort(int (*cmp)(void *, void *), void *arr, int n) {
}

float *mk(void) {
}

int log_msg(char *fmt, ...) {
}

